// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace example {

    export enum Corpus {
        UNIVERSAL = 0,
        WEB = 1,
        IMAGES = 2,
        LOCAL = 3,
        NEWS = 4,
        PRODUCTS = 5,
        VIDEO = 6,
    }
    export interface SearchRequest {
        query?: string;
        pageNumber?: number;
        resultPerPage?: number;
        corpus?: Corpus;
        sentAt?: google.protobuf.Timestamp;
        xyz?: { [key: string]: number };
        zytes?: Uint8Array;
    }

    export interface SearchResponse {
        results?: Array<string>;
        numResults?: number;
        originalRequest?: SearchRequest;
    }

}

