// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace nested {

    // Comment for Notification
    export interface Notification {
        // Comment for Notification.message_type
        message_type?: Notification.Type;
        // Comment for Notification.content
        content?: string;
    }

    export namespace Notification {
        // Comment for Notification.Type
        export enum Type {
            UNSPECIFIED = 0,
            TEXT = 1,
            VIDEO = 2,
            AUDIO = 3,
        }
    }

    export interface Tweet {
        tweet_type?: Tweet.Type;
        content?: string;
    }

    export namespace Tweet {
        // Comment for Tweet.Type
        export enum Type {
            UNSPECIFIED = 0,
            ORIGINAL = 1,
            RETWEET = 2,
        }
    }

    export interface A {
        id?: string;
        b?: A.B;
    }

    export namespace A {
        export interface B {
            id?: string;
        }

    }

}

