// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace routeguide {

    export interface Point {
        latitude?: number;
        longitude?: number;
    }

    export interface Rectangle {
        lo?: Point;
        hi?: Point;
    }

    export interface Feature {
        name?: string;
        location?: Point;
    }

    export interface RouteNote {
        location?: Point;
        message?: string;
    }

    export interface RouteSummary {
        point_count?: number;
        feature_count?: number;
        distance?: number;
        elapsed_time?: number;
    }

    export interface RouteGuideService {
        GetFeature: (r:Point) => Feature;
        ListFeatures: (r:Rectangle, cb:(a:{value: Feature, done: boolean}) => void) => void;
        RecordRoute: (r:() => {value: Point, done: boolean}) => RouteSummary;
        RouteChat: (r:() => {value: RouteNote, done: boolean}, cb:(a:{value: RouteNote, done: boolean}) => void) => void;
    }
}

