import * as google_protobuf from "google/protobuf/timestamp"
// import * as google_api from "google/api/field_behavior" // not used 
// import * as opts from "opts/opts" // not used 

// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace example_with_field_options {

    // SearchRequest is an example type representing a search query.
    export interface SearchRequest {
        query?: string;
        pageNumber?: number;
        // Number of results per page.
        resultPerPage?: number; // Should never be zero.
        corpus?: SearchRequest.Corpus;
        sentAt?: google_protobuf.Timestamp;
        xyz?: { [key: string]: number };
        zytes?: Uint8Array;
        exampleRequired: number;
    }

    export namespace SearchRequest {
        export enum Corpus {
            UNIVERSAL = "UNIVERSAL",
            WEB = "WEB",
            IMAGES = "IMAGES",
            LOCAL = "LOCAL",
            NEWS = "NEWS",
            PRODUCTS = "PRODUCTS",
            VIDEO = "VIDEO",
        }
        export interface XyzEntry {
            key?: string;
            value?: number;
        }

    }

    export interface SearchResponse {
        results: Array<string>;
        numResults: number;
        originalRequest: SearchRequest;
        nextResultsUri?: string;
    }

}

