// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace nested {

    export interface Notification {
        messageType?: Notification.Type;
        content?: string;
    }

    export namespace Notification {
        export enum Type {
            UNSPECIFIED = "UNSPECIFIED",
            TEXT = "TEXT",
            VIDEO = "VIDEO",
            AUDIO = "AUDIO",
        }
    }

    export interface Tweet {
        tweetType?: Tweet.Type;
        content?: string;
    }

    export namespace Tweet {
        export enum Type {
            UNSPECIFIED = "UNSPECIFIED",
            ORIGINAL = "ORIGINAL",
            RETWEET = "RETWEET",
        }
    }

    export interface A {
        id?: string;
        b?: A.B;
    }

    export namespace A {
        export interface B {
            id?: string;
        }

    }

}

