// Code generated by protoc-gen-tstypes. DO NOT EDIT.

export interface DoubleValue {
    value?: number;
}

export interface FloatValue {
    value?: number;
}

export interface Int64Value {
    value?: number;
}

export interface UInt64Value {
    value?: number;
}

export interface Int32Value {
    value?: number;
}

export interface UInt32Value {
    value?: number;
}

export interface BoolValue {
    value?: boolean;
}

export interface StringValue {
    value?: string;
}

export interface BytesValue {
    value?: Uint8Array;
}

