// Code generated by protoc-gen-tstypes. DO NOT EDIT.

export enum NullValue {
    NULL_VALUE = "NULL_VALUE",
}
export interface Struct_FieldsEntry {
    key?: string;
    value?: Value;
}

export interface Struct {
    fields?: { [key: string]: Value };
}

export interface Value {
    nullValue?: NullValue;
    numberValue?: number;
    stringValue?: string;
    boolValue?: boolean;
    structValue?: Struct;
    listValue?: ListValue;
}

export interface ListValue {
    values?: Array<Value>;
}

