// Code generated by protoc-gen-tstypes. DO NOT EDIT.

export enum Type {
    UNSPECIFIED = "UNSPECIFIED",
    TEXT = "TEXT",
    VIDEO = "VIDEO",
    AUDIO = "AUDIO",
}
export interface Notification {
    messageType?: Type;
    content?: string;
}

export enum Type {
    UNSPECIFIED = "UNSPECIFIED",
    ORIGINAL = "ORIGINAL",
    RETWEET = "RETWEET",
}
export interface Tweet {
    tweetType?: Type;
    content?: string;
}

