// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace nested {

    export enum Type {
        UNSPECIFIED = "UNSPECIFIED",
        TEXT = "TEXT",
        VIDEO = "VIDEO",
        AUDIO = "AUDIO",
    }
    export interface Notification {
        message_type?: Type;
        content?: string;
    }

    export enum Type {
        UNSPECIFIED = "UNSPECIFIED",
        ORIGINAL = "ORIGINAL",
        RETWEET = "RETWEET",
    }
    export interface Tweet {
        tweet_type?: Type;
        content?: string;
    }

}

