// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace example {

    export enum Corpus {
        UNIVERSAL = "UNIVERSAL",
        WEB = "WEB",
        IMAGES = "IMAGES",
        LOCAL = "LOCAL",
        NEWS = "NEWS",
        PRODUCTS = "PRODUCTS",
        VIDEO = "VIDEO",
    }
    export interface SearchRequest {
        query?: string;
        pageNumber?: number;
        resultPerPage?: number;
        corpus?: Corpus;
        sentAt?: google.protobuf.Timestamp;
        xyz?: { [key: string]: number };
        zytes?: Uint8Array;
    }

    export interface SearchResponse {
        results?: Array<string>;
        numResults?: number;
        originalRequest?: SearchRequest;
    }

}

