// Code generated by protoc-gen-go. DO NOT EDIT.
// source: opts.proto

package opts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Options struct {
	Required             *bool    `protobuf:"varint,1,opt,name=required" json:"required,omitempty"`
	Nullable             *bool    `protobuf:"varint,2,opt,name=nullable" json:"nullable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_f695bd055fd0de95, []int{0}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetRequired() bool {
	if m != nil && m.Required != nil {
		return *m.Required
	}
	return false
}

func (m *Options) GetNullable() bool {
	if m != nil && m.Nullable != nil {
		return *m.Nullable
	}
	return false
}

var E_FieldDefaults = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*Options)(nil),
	Field:         1035,
	Name:          "opts.field_defaults",
	Tag:           "bytes,1035,opt,name=field_defaults",
	Filename:      "opts.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Options)(nil),
	Field:         1035,
	Name:          "opts.field",
	Tag:           "bytes,1035,opt,name=field",
	Filename:      "opts.proto",
}

func init() {
	proto.RegisterType((*Options)(nil), "opts.Options")
	proto.RegisterExtension(E_FieldDefaults)
	proto.RegisterExtension(E_Field)
}

func init() { proto.RegisterFile("opts.proto", fileDescriptor_f695bd055fd0de95) }

var fileDescriptor_f695bd055fd0de95 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2f, 0x28, 0x29,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0xa5, 0x14, 0xd2, 0xf3, 0xf3, 0xd3,
	0x73, 0x52, 0xf5, 0xc1, 0x62, 0x49, 0xa5, 0x69, 0xfa, 0x29, 0xa9, 0xc5, 0xc9, 0x45, 0x99, 0x05,
	0x25, 0xf9, 0x45, 0x10, 0x75, 0x4a, 0x8e, 0x5c, 0xec, 0xfe, 0x05, 0x25, 0x99, 0xf9, 0x79, 0xc5,
	0x42, 0x52, 0x5c, 0x1c, 0x45, 0xa9, 0x85, 0xa5, 0x99, 0x45, 0xa9, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x1c, 0x41, 0x70, 0x3e, 0x48, 0x2e, 0xaf, 0x34, 0x27, 0x27, 0x31, 0x29, 0x27, 0x55, 0x82,
	0x09, 0x22, 0x07, 0xe3, 0x5b, 0x05, 0x73, 0xf1, 0xa5, 0x65, 0xa6, 0xe6, 0xa4, 0xc4, 0xa7, 0xa4,
	0xa6, 0x25, 0x96, 0xe6, 0x94, 0x14, 0x0b, 0xc9, 0xe8, 0x41, 0xec, 0xd5, 0x83, 0xd9, 0xab, 0xe7,
	0x96, 0x99, 0x93, 0x0a, 0xb5, 0x47, 0xa2, 0x9b, 0x43, 0x81, 0x51, 0x83, 0xdb, 0x88, 0x57, 0x0f,
	0xec, 0x5c, 0xa8, 0x68, 0x10, 0x2f, 0xd8, 0x0c, 0x17, 0xa8, 0x11, 0x56, 0xce, 0x5c, 0xac, 0x60,
	0x01, 0x21, 0x59, 0x2c, 0x66, 0xa5, 0xe6, 0xa4, 0xe0, 0x37, 0x0c, 0xa2, 0x17, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xa2, 0x5d, 0xfc, 0x8f, 0x11, 0x01, 0x00, 0x00,
}
