on:
  push: 
    branches: 
      - refs/tags/*
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: goreleaser
      uses: docker://goreleaser/goreleaser
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      with:
        args: release --config=.github/.goreleaser.yml
