 on:
   push: 
     branches: 
       - refs/*
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: ls -alh
    - name: goreleaser
      uses: docker://goreleaser/goreleaser
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      with:
        args: release --skip-publish
